# Generated by Django 4.1.5 on 2023-02-04 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import meetings.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0002_rename_user_meeting'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to=meetings.models.upload_location)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('location', models.CharField(max_length=120)),
                ('participating_users', models.CharField(max_length=120)),
                ('time', models.DateTimeField()),
                ('activity', models.CharField(max_length=120)),
                ('active', models.BooleanField()),
                ('is_private', models.BooleanField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
